backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: 'docs'
    label: 'Docs'
    format: 'json'
    folder: 'docs/'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'ID', name: 'id', widget: 'string' }
      - { label: 'Title', name: 'title', widget: 'staring' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
